# Everything in this file is case-sensitive and should be lowercase. Whitespace at start / end of line, or either side of =, is fine.
# Boolean values: "true" is true. Anything else (1, "True", etc) is false.
# Comments: Prepend whole line comments with # or ;. Prepend mid-line comments only with ;. Whitespace before # in a whole-line comment is okay.
# Lists: Values should be comma-seperated. Whitespace either side of the comma is fine.

[core]
timeout=5
include_channel_count_in_status=true

[printer]
comm=uart_en
uart_instance=0
tx_pin=0
rx_pin=1
en_pin=2

[uart_multi_0]
uart_instance=1
tx_pin=4
rx_pin=5

[mmu_0]
multi_id=0
en_pin=6

[mmu_1]
multi_id=0
en_pin=7

[peripheral_0]
type=rng
min=-2500
max=10000
report_f13=true
