; ---------------
; Wiring settings
; ---------------

; Hardware UART channel number and TX/RX/EN pins to use for communication with the printer.
PRINTER_UART=0
PRINTER_TX_PIN=0
PRINTER_RX_PIN=1
PRINTER_EN_PIN=2

; Hardware UART channel number and TX/RX pins to use for communication with the IFSes. Note
; that all IFSes (or rather, their MAX3485 chips) should be wired in parallel to a single UART.
IFS_UART=1
IFS_TX_PIN=4
IFS_RX_PIN=5

; IFS EN pins. To add additional IFSes, add their EN pin numbers to this list. You can add as
; many IFSes as you have spare GPIO pins (and power supply, and X-in-1 tubing) for. Seperate
; IDs with commas.
IFS_EN_PINS=6,7

; --------------
; Other settings
; --------------

; Log settings. Set LOGGING to False to disable logging altogether. LOG_FILE_MAX_SIZE specifies
; the maximum size in bytes that the log file may grow to before a second log file is started.
; When the second log file fills, the first one is erased and a third is started, and so on. Note
; that this is not an exact limit - it is only checked upon completing a flush-to-file, so files
; may go slightly over this limit in practice.
LOGGING=True
LOG_FILE_MAX_SIZE=131072

; Initial passthrough target. If set to -1, the splitter will already be in splitter mode when
; starting up. Otherwise, it will be in passthrough mode until changed into splitter mode.
INITIAL_PASSTHROUGH_TARGET=-1